layout_spectrum: 0.4766349011670687
typography_spectrum: 0.40647438625288707
color:
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  brandStrength: 0.9295527615158422
  lightness: 0.10174403500208391
  saturation: 0.9695994321209849
  rhythmicContrast: 0.852024545756141
coverPrefs:
  filter: false
content_rating:
  adult: false
github: true
opengraph:
  type: ''
  appId: ''
author:
  name: Fabio Bruna
  url: ''
  email: f.bruna@xs4all.nl
name: fabiobruna
navigation:
  - name: Github
    url: 'http://github.com/fabiobruna'
    type: external
title: Fabio Bruna
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c39f9952-f909-4b65-a112-c50db5914de4.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c39f9952-f909-4b65-a112-c50db5914de4.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
