name: fabiobruna
layout_spectrum: 0.18406663998030126
typography_spectrum: 0.484228327171877
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.580727766500786
  lightness: 0.49668725952506065
  saturation: 0.1844853137154132
  rhythmicContrast: 0.2886874028481543
title: Mijn weblogement
author:
  name: Fabio Bruna
  url: ''
  email: f.bruna@xs4all.nl
content_rating:
  adult: false
